// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresDatabase.Contexts;

#nullable disable

namespace PostgresDatabase.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20230404164902_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Generic.ServiceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_timestamp");

                    b.Property<DateTime?>("StopTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stop_timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("session_pkey");

                    b.ToTable("session", "main");

                    b.HasDiscriminator<string>("Type").HasValue("session_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Generic.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discriminator");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_timestamp");

                    b.Property<DateTime?>("LeaveTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leave_timestamp");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("player_pkey");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_player_session_id");

                    b.ToTable("player", "main");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Player");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Factorio.FactorioSession", b =>
                {
                    b.HasBaseType("Domain.Entities.Generic.ServiceSession");

                    b.HasDiscriminator().HasValue("factorio");
                });

            modelBuilder.Entity("Domain.Entities.Factorio.FactorioPlayer", b =>
                {
                    b.HasBaseType("Domain.Entities.Generic.Player");

                    b.HasDiscriminator().HasValue("FactorioPlayer");
                });

            modelBuilder.Entity("Domain.Entities.Generic.Player", b =>
                {
                    b.HasOne("Domain.Entities.Generic.ServiceSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .HasConstraintName("fk_player_game_session_session_id");

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
